apiVersion: v1
kind: Pod
metadata:
  name: "giropops-pod"
  labels:
    app: "giropops-pod"
spec:
  containers:
  - name: giropops-container
    image: nginx
    resources: {}
    env:
    - name: USERNAME
      valueFrom:
        secretKeyRef:
          name: giropops-secret
          key: username
    - name: PASSWORD
      valueFrom:
        secretKeyRef:
          name: giropops-secret
          key: password
