apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  selector:
    app: nginx-https
  type: NodePort
  ports:
  - name: nginx-service
    protocol: TCP
    port: 443
    targetPort: 443
    nodePort: 32400