apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: nginx-prometheus-rule
  namespace: monitoring
  labels:
    prometheus: k8s
    role: alert-rules
    app.kubernetes.io/name: kube-prometheus
    app.kubernetes.io/part-of: kube-prometheus
spec:
  groups:
  - name: nginx-prometheus-rule
    rules:
    - alert: NginxDown
      expr: up{job="nginx"} == 0
      for: 1m
      labels:
        severity: critical
      annotations:
        summary: "nginx está parado"
        description: "Nginx is down por mais de 1 minuto. Pod name: {{ $labels.pod}}"

    - alert: NginxHighRequestRate
      expr: rate(nginx_http_requests_total{job="nginx"}[5m]) > 10
      for: 1m
      labels:
        secerity: warning
      annotations:
        summary: "Nginx is receiving high request rate"
        description: "Nginx is receiving high request rate for more than 1 minute. Pod name: {{ $labels.pod }}"
