apiVersion: v1
kind: PersistentVolume
metadata:
  name: meu-pv-nfs-0
  labels:
    storage: nfs
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  nfs:
    server: 172.25.44.204
    path: "/mnt/nfs/"
  storageClassName: nfs