apiVersion: v1
kind: Pod
metadata:
  labels:
    run: nginx-giropops
    app: giropops-strigus
  name: nginx-giropops
spec:
  containers:
  - image: nginx
    name: nginx-giropops
    ports:
    - containerPort: 80
    resources: 
      limits: 
        memory: "4400Mi"
        cpu: "500m"
      requests:
        memory: "4400Mi"
        cpu: "300m"
  dnsPolicy: ClusterFirst
  restartPolicy: Always
