apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-nfs-0
  labels:
    storage: nfs
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: nfs
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: "/mnt/nfs/"
    server: 172.25.44.204
