apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx-deployment
    fruta: banana
  namespace: giropops
spec:
  replicas: 6
  selector:
    matchLabels:
      app: nginx-deployment
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 0
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: nginx-deployment
    spec:
      containers:
      - name: nginx-opa
        image: nginx:1.14.0
        resources:
          limits:
            memory: "128Mi"
            cpu: "0.9"
          requests:
            cpu: "0.3"
            memory: 64Mi

